# Generated by Django 5.1.2 on 2024-10-26 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='coords',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perevals.coordinates', verbose_name='Координаты перевала'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='level',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perevals.perevallevel', verbose_name='Сложность во времена года'),
        ),
    ]
