# Generated by Django 5.1.2 on 2024-10-26 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevals', '0002_alter_pereval_coords_alter_pereval_level'),
        ('users', '0002_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='Добавил пользователь'),
        ),
    ]
