# Generated by Django 5.1.2 on 2024-10-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevals', '0003_alter_pereval_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pereval',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Статус модерации'),
        ),
    ]
