# Generated by Django 5.1.2 on 2024-10-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя пользователя')),
                ('fam', models.CharField(max_length=32, verbose_name='Фамилия пользователя')),
                ('otc', models.CharField(blank=True, max_length=32, null=True, verbose_name='Отчество пользователя')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Эл. почта')),
            ],
        ),
    ]
